---
name: Package-Subroutine
version: 0.18
author:
  - 'Sebastian Knapp <sk@computer-leipzig.com>'
abstract: minimalistic import/export and other util package functions
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Perl6::Junction: 1.30000
  perl: 5.6.0
build_requires:
  ExtUtils::Manifest: 0
  IO::File: 0
  Test::More: 0
provides:
  Package::Subroutine:
    file: lib/Package/Subroutine.pm
    version: 0.18
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
